AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Stack for Wordpress
  
Parameters:
  WebSecurityGroup:
    Type: String
  SubnetId:
    Type: String
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
  AmiType:
    Description: Type of AMI
    Type: String
  DBName:
    Description: The WordPress database name
    Type: String
  MasterUsername:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String
  MasterUserPassword:
    NoEcho: 'true'
    Description: The WordPress database admin account password
    Type: String
  DBEndpoint:
    Description: Database EndPoint code
    Type: String
  KeyName: 
    Type: AWS::EC2::KeyPair::KeyName

Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
          InstanceType: !Ref InstanceType
          ImageId: !Ref AmiType
          KeyName: !Ref KeyName
           UserData:
            Fn::Base64:                              
              !Sub |
                  #!/bin/bash 
                  yum update -y
                  yum install httpd 
                  yum install -y amazon-linux-extras
                  amazon-linux-extras enable php7.4 
                  yum clean metadata -y
                  yum install php php-{pear,cgi,common,curl,mbstring,gd,mysqlnd,gettext,bcmath,json,xml,fpm,intl,zip,imap} -y
                  cd /var/www/html
                  echo "Healthy" > healthy.html
                  wget https://wordpress.org/latest.tar.gz
                  tar -xzf latest.tar.gz
                  cp -r wordpress/* /var/www/html/
                  rm -r wordpress
                  rm -rf latest.tar.gz
                  chmod -R 755 wp-content
                  chown -R apache:apache wp-content
                  chkconfig httpd on

                  sed -i 's/database_name_here/${DBName}/g' wp-config-sample.php
                  sed -i 's/username_here/${MasterUsername}/g' wp-config-sample.php
                  sed -i 's/password_here/${MasterUserPassword}/g' wp-config-sample.php
                  sed -i 's/localhost/${DBEndpoint}/g' wp-config-sample.php

                  curl https://api.wordpress.org/secret-key/1.1/salt/ --output saltKey.txt
                  sed -i -e '/AUTH_KEY/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/LOGGED_IN_KEY/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/NONCE_KEY/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/AUTH_SALT/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/SECURE_AUTH_SALT/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/LOGGED_IN_SALT/{r saltKey.txt/1' -e 'd}' wp-config-sample.php
                  sed -i -e '/NONCE_SALT/{r saltKey.txt' -e 'd}' wp-config-sample.php

                  mv wp-config-sample.php wp-config.php
                  
                  service httpd start
          NetworkInterfaces: 
            - AssociatePublicIpAddress: "true"
              DeviceIndex: "0"
              GroupSet: 
                - Ref: WebSecurityGroup
              SubnetId: 
                Ref: SubnetId

Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !GetAtt EC2Instance.PublicIp