AWSTemplateFormatVersion: "2010-09-09"
Description: Route 53 Stack for test cloudformation

Parameters:
  PublicIp: 
    Type: String

Resources:
  myDNSRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z2LZ45JUYPDLLV
      Name: dweiskopf.training.trambo.cloud
      Type: A
      TTL: '900'
      ResourceRecords: [!Ref PublicIp]
